namespace alm.Other.Enums
{
    public enum TokenType
    {
        tkAssign,
        tkAddAssign,
        tkSubAssign,
        tkIDivAssign,
        tkFDivAssign,
        tkMultAssign,
        tkPowerAssign,
        tkRemndrAssign,
        tkLShiftAssign,
        tkRShiftAssign,
        tkBitwiseOrAssign,
        tkBitwiseAndAssign,
        tkBitwiseXorAssign,

        tkType,
        tkIntConst,
        tkCharConst,
        tkRealConst,
        tkArrayConst,
        tkStringConst,
        tkBooleanConst,

        tkPlus,
        tkPower,
        tkMinus,
        tkMult,
        tkIDiv,
        tkFDiv,
        tkRemndr,
        tkLShift,
        tkRShift,
        tkBitwiseOr,
        tkBitwiseAnd,
        tkBitwiseXor,

        tkOr,
        tkXor,
        tkNot,
        tkAnd,
        tkLess,
        tkEqual,
        tkGreater,
        tkNotEqual,
        tkEqualLess,
        tkEqualGreater,

        tkDo,
        tkIf,
        tkFor,
        tkRet,
        tkElse,
        tkWhile,
        tkBreak,
        tkImport,
        tkContinue,

        tkAt, //@
        tkLbra,
        tkRbra,
        tkLpar,
        tkRpar,
        tkComma,
        tkColon,
        tkSqLbra,
        tkSqRbra,
        tkDQuote,
        tkSQuote,
        tkSemicolon,

        tkIdentifier,
        tkOf,
        tkFunc,
        tkGlobal,
        tkExternalProp,

        tkNull,
        tkEOF
    }
}
